CREATE SCHEMA `locacao` ;

CREATE TABLE usuario (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
matricula VARCHAR(100),
senha VARCHAR(45),
email VARCHAR(100),
telefone VARCHAR(100),
ativo VARCHAR(1),
PRIMARY KEY (`id`),
UNIQUE INDEX `id` (`id` ASC)
)

CREATE TABLE unidade(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100),
telefone VARCHAR(100),
endereco VARCHAR(200) NULL,
ativo VARCHAR(1),
PRIMARY KEY (`id`),
UNIQUE INDEX `id` (`id` ASC)
)

CREATE TABLE instituicao(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100),
telefone VARCHAR(100),
ativo VARCHAR(1),
PRIMARY KEY (`id`),
UNIQUE INDEX `id` (`id` ASC)
)

CREATE TABLE funcao(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
descricao VARCHAR(100),
ativo VARCHAR(1),
PRIMARY KEY (`id`),
UNIQUE INDEX `id` (`id` ASC)
)

CREATE TABLE tipo_recurso (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
ativo VARCHAR(1),
PRIMARY KEY (`id`),
UNIQUE INDEX `id` (`id` ASC)
)

CREATE TABLE restricao_recurso(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
id_tipo_recurso INT NOT NULL,
id_funcao INT NOT NULL,
PRIMARY KEY (`id`),
UNIQUE INDEX `id` (`id` ASC)
)

CREATE TABLE recurso (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
etiqueta VARCHAR(100) NULL,
observacao VARCHAR(100) NULL,
id_unidade INT NOT NULL,
id_tipo_recurso INT NOT NULL,
ativo VARCHAR(1),
PRIMARY KEY (`id`),
UNIQUE INDEX `id` (`id` ASC)
)

CREATE TABLE reserva (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
id_responsavel INT NOT NULL,
id_destinatario INT NOT NULL,
data_hora_reserva TIMESTAMP NOT NULL,
data_hora_final TIMESTAMP NOT NULL,
repeticao VARCHAR(100), --EVENTO UNICO / SEMANALMENTE A CADA SEGUNDA / SEMANALMENTE A CADA TERCA / ...TODOS OS DIAS DA SEMANA / TODOS OS DIAS
status VARCHAR(50), --ATIVO / PENDENTE / CONCLUIDO
PRIMARY KEY (`id`),
UNIQUE INDEX `id` (`id` ASC)
)

CREATE TABLE repeticao (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
id_reserva INT NOT NULL,
id_responsavel INT NOT NULL,
id_destinatario INT NOT NULL,
data_hora_reserva TIMESTAMP NOT NULL,
data_hora_final TIMESTAMP NOT NULL,
ativo VARCHAR(1), --ATIVO / INATIVO
PRIMARY KEY (`id`),
UNIQUE INDEX `id` (`id` ASC)
)